### ISSUE TITLE
source_pads_surface is broken

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#59]
The source_pads_surface vertex generator doesn't work. Tested source_pads_external_surface and source_pads_internal_surface and they are both fine, so it's the act of combining them that isn't set up properly.

```
flsimulate : Setup/run of simulation threw exception
[virtual void genvtx::combined_vg::initialize(const ::datatools::properties &, ::datatools::service_manager &, ::genvtx::vg_dict_type &):349: Vertex generator 'source_pads_internal_surface' has no weight information in combined vertex generator 'source_pads_surface' !]

```
Guessing this just missing a weight so it's probably an easy fix if you know where the file is and what weights you want to use. But I don't.

**Comment by fmauger** [comment]
A PR has been submitted.

**Comment by cherylepatrick** [comment]
I've installed Falaise 3.2.0 and I am still seeing this. I looked at ~/CadfaelBrew/share/Falaise-3.2.0/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/source_vg.def
 and it is still the old version with the bug. Am I missing something?

**Comment by fmauger** [comment]
Hum! I though it was fixed. I have to check. Maybe it is still blocked in some of my branches.
Let me have a look ASAP !

**Comment by cherylepatrick** [comment]
Thanks @fmauger ! It might be that I installed it wrongly...

**Comment by goliviero** [comment]
Same issue here, I intalled Falaise 3.2.0 and still get the error.
I think I've got the solution, the PR https://github.com/SuperNEMO-DBD/Falaise/pull/60 hasn't been approved and merged on the develop branch...
The error is still here on this file : https://github.com/SuperNEMO-DBD/Falaise/blob/develop/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/source_vg.def
``
[name="source_pads_surface" type="genvtx::combined_vg"]
generators.source_pads_external_bulk.absolute_weight : real  =  250.0 # 125 mm * 2
generators.source_pads_internal_bulk.absolute_weight : real  = 4607.0 # 135.5 mm * 34
``
'bulk' has to be 'surface'
